apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
  namespace: {{ .Release.Namespace }}
data:
  PORT: "5001"
  SERVICE_NAME: auth-service
  DB_HOST: swiftmart-postgres.ccnwaycacsuq.us-east-1.rds.amazonaws.com
  DB_PORT: "5432"
  DB_NAME: swiftmart_db
  DB_SSL: "true"
