apiVersion: v1
kind: Secret
metadata:
  name: order-secret
  namespace: swiftmart
type: Opaque
stringData:
  DB_USER: postgres
  DB_PASSWORD: postgres
  JWT_SECRET: swiftmart_secret_key
  INTERNAL_SERVICE_TOKEN: swiftmart_internal_token
