apiVersion: v1
kind: Secret
metadata:
  name: cart-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  DB_USER: postgres
  DB_PASSWORD: password123
  JWT_SECRET: swiftmart_secret_key