apiVersion: v1
kind: ConfigMap
metadata:
  name: product-config
  namespace: {{ .Release.Namespace }}
data:
  PORT: "5002"
  SERVICE_NAME: product-service
  DB_HOST: {{ .Values.database.host | quote }}
  DB_PORT: {{ .Values.database.port | quote }}
  DB_NAME: {{ .Values.database.name | quote }}
  DB_SSL: {{ .Values.database.ssl | quote }}
  REDIS_URL: redis://swiftmart-redis.ycv67f.0001.use1.cache.amazonaws.com:6379
