apiVersion: v1
kind: ConfigMap
metadata:
  name: order-config
  namespace: {{ .Release.Namespace }}
data:
  PORT: "5003"
  SERVICE_NAME: order-service
  DB_HOST: {{ .Values.database.host | quote }}
  DB_PORT: {{ .Values.database.port | quote }}
  DB_NAME: {{ .Values.database.name | quote }}
  DB_SSL: {{ .Values.database.ssl | quote }}
  AWS_REGION: {{ .Values.messaging.awsRegion | quote }}
  ORDER_EVENTS_TOPIC_ARN: {{ .Values.messaging.orderEventsTopicArn | quote }}
